# Generated by Django 3.0.7 on 2025-08-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
