# Generated by Django 3.0.7 on 2025-08-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_id', models.CharField(max_length=20, unique=True)),
                ('registration_date', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('father_qualification', models.CharField(blank=True, max_length=100)),
                ('father_designation', models.CharField(blank=True, max_length=100)),
                ('father_office_address', models.TextField(blank=True)),
                ('father_phone', models.CharField(blank=True, max_length=15)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_aadhaar', models.CharField(blank=True, max_length=12)),
                ('father_signature', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_qualification', models.CharField(blank=True, max_length=100)),
                ('mother_designation', models.CharField(blank=True, max_length=100)),
                ('mother_office_address', models.TextField(blank=True)),
                ('mother_phone', models.CharField(blank=True, max_length=15)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_aadhaar', models.CharField(blank=True, max_length=12)),
                ('mother_signature', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('std', models.CharField(default='Unknown', max_length=100)),
                ('division', models.CharField(default='A', max_length=5)),
                ('address', models.CharField(default='Unknown', max_length=255)),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Home.Parent')),
            ],
        ),
    ]
